---
title: "Python 3 Exceptions: как понять и исправить ошибки"
slug: python-3-exceptions-how-to-understand-and-fix-errors-ru
date: "2020-07-27"
description: "Эта статья для тех, кто хочет понять Python Exceptions, почему они возникают и как решить проблему на которую указывают Exceptions."
lang: ru
---

Эта статья для тех, кто хочет понять **Python Exceptions**, почему они возникают и как решить проблему на которую указывают Exceptions.

Статья написана для программистов начинающих свое знакомство с Python. Поэтому статья содержит объяснения основных концепций языка и написана с минимальным количеством терминов.

**Exception** (*рус. эксепшион*) так же может встречаться в русском языке как исключение или ошибка.

В статье рассмотрены исключения для **Python** от **версии 3.5 до 3.8**. Для версий старше 3.8 этот список должен быть актуальным. Для версий младше 3.5 могут быть неточности. Эта статья наверняка будет содержать не точности для Python 2-ых версий.

## Python SyntaxError

SyntaxError или синтаксическая ошибка указывает на не верное использование синтаксиса Python.

> **Синтаксис** языка программирования — набор правил, описывающий комбинации символов алфавита, считающиеся правильно структурированной программой (документом) или её фрагментом.
> 
> [Wikipedia](https://ru.wikipedia.org/wiki/%D0%A1%D0%B8%D0%BD%D1%82%D0%B0%D0%BA%D1%81%D0%B8%D1%81_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5))

### Примеры SyntaxError

Забытые двоеточия в `for` циклах:

```
array = [1,2,3,4,5]
for item in array
    print(item)
```

```
  File python-3-exceptions/example.py, line 2
    for item in array
                    ^
SyntaxError: invalid syntax
```

или `if` операторах:

```
a = 5
if a > 10
    a = 0
print(a)
```

```
  File python-3-exceptions/example.py, line 2
    if a > 10
            ^
SyntaxError: invalid syntax
```

или определении (написании) функций:

```
def add(a, b)
    a + b

print(add(10, 278))
```

```
  File python-3-exceptions/example.py, line 1
    def add(a, b)
                ^
SyntaxError: invalid syntax
```

Во всех случаях был забыт знак двоеточия в структуре кода. Вот тот же самый код с правильным ситаксисом.

```
def add(a, b):
    return a + b

array = [1, 2, 3, 4, 5]

if (add(10, 217) > 100):
   array = [100, 200, 300, 400, 500]

for item in array:
    print(item)
```

или попытались использовать не корректное имя для переменной:

```
2name = 'Dmitry Vladimir'

many@ = 1000000

className = 'Computer Science Course'
```

Синтаксическая ошибка означает что вы написали код который не имеет смысла с точки зрения языка программирования. Как если бы мы сказали: и в то иначе как бы так. Это все настоящие части русского языка но вместе они не имеет никакого смысла.

### Как исправить SyntaxError

- ищите забытую запятую, скобку, двоеточие, математический знак;
- ищите использование ключевого слова в виде переменной;
- ищите переменную с не разрешенным именем, начинающуюся с цифры имеющие символы отличные от `_`;

Ошибка подскажет в какой строке у вас не правильный синтаксис:

`File python-3-exceptions/example.py, line 13`

В данном примере синтаксическая ошибка произошла на строке 13.

### Список ключевых слов в Python

```
['False', 'None', 'True', 'and', 'as', 'assert', 'async',
 'await', 'break', 'className', 'continue', 'def', 'del', 'elif',
 'else', 'except', 'finally', 'for', 'from', 'global', 'if',
 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass',
 'raise', 'return', 'try', 'while', 'with', 'yield']
```

Данный список можно получить выполнив код:

```
import keyword
print(keyword.kwlist)
```

Подробнее про [keyword](https://docs.python.org/3.7/library/keyword.html).

### Разрешенные символы в именах переменных

В именах переменных Python можно использовать заглавные и прописные латинские буквы `A-Z` и `a-z`, а также числа `0-9` и знак подчеркивания (underscore) `_`.

Числа в имени разрешены, но переменная не должна начинаться с чисел. `2word` не разрешенное имя, `word2` разрешенное имя.

Переменные можно начинать со знака подчеркивания `_` но это имеет особый смысл для Python программистов. Переменные `_cache` или `_data` или любое другое имя переменной начинающееся с подчеркивания означают, что они предназначены только для внутреннего использования в текущем кусочке кода. Поэтому используйте имена начинающиеся с подчеркивания по назначению. Если не уверены не используйте подчеркивание в начале имени переменной.

Подчеркивание можно и нужно использовать в составных именах переменных. Например: `company_name`, `previous_chosen_option`, `post_title_image`.

## Python TypeError

TypeError *(рус. тайп эрор)* возникает, когда операция или функция применяется к объекту неподходящего типа.

> В программировании **data type** *(рус. дата тайп)*, **тип данных** или просто **тип** - это такой атрибут данных, которое сообщает программе как эти данные будут использованы.

```
def add(a, b):
    return a + b

add(10, '217')
```

Ошибка

```
Traceback (most recent call last):
  File python-3-exceptions/example.py, line 4, in <module>
    add(10, '217')
  File python-3-exceptions/example.py, line 2, in add
    return a + b
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

Python умеет складывать числа между собой, но не умеет складывать число со строкой. Это связано с тем что число как тип данных не знает как прибавлять к себе строку. Так как эта проблема между типов, то в результате мы получаем TypeError.

Решением может быть либо передача двух чисел, либо двух строк.

```
def add(a, b):
    return a + b

add('двадцать', 'три') # => 'двадцатьтри'
add(20, 3) # => 23
```

Другой пример TypeError, когда мы вызываем операцию, которая не может быть исполнена для типа данных:

```
name = 30
name[0]
```

Ошибка:

```
Traceback (most recent call last):
  File python-3-exceptions/example.py, line 2, in <module>
    name[0]
TypeError: 'int' object is not subscriptable
```

Обратите внимание на то, что в переменную `name` я назначил числовой тип данных *(далее я буду использовать термин число)*. Что не имеет смысла, но это частый источник ошибок. Переменная имеет не верное имя и мы ожидаем что можем вызвать определенные операции над ней.

```
name = 'Dmitry'
name[0] # => 'D'
```

### Как исправить TypeError

- убедитесь правильные ли типы вы передаете в вызываемые функции;
- убедитесь что вы используете правильные типы с операторами `+`, `-`, `/`, `*`, и другими
- убедитесь что переменная имеет именно тот тип данных метод который вы вызываете у нее

### object is not callable, особенный случай TypeError

Если вы попытаетесь вызвать функцию, а она вам вернет `TypeError: <тут будет подставлено имя типа данных> object is not callable` значит вы вызываете не функцию.

Пример:

```
five = 5
five()
```

Ошибка:

```
Traceback (most recent call last):
  File python-3-exceptions/example.py, line 2, in <module>
    five()
TypeError: 'int' object is not callable
```

Часто такое случается при случайном использовании имени уже определенной функции для переменной в вашем коде:

```
age = [1, 2, 23, 62]
weight = [4.5, 4.8, 44.2, 57.9]
max = max(age)
max(weight)
```

`max` функция встроенная в язык Python была переназначена на значение из вызова функции `max(age)` что дало результат `62` в данном случае. После строчки `max = max(age)` имя `max` уже не хранит в себе функцию для вычисления максимального значения, теперь `max` хранит число `62`. Отсюда ошибка:

```
Traceback (most recent call last):
  File python-3-exceptions/example.py, line 4, in <module>
    max(weight)
TypeError: 'int' object is not callable
```

В случае `object is not callable` ищите где вы использовали имя функции для своей переменной. Предпоследняя строчки в Traceback подскажет имя переменной и функции которые конфликтуют. В примере выше `File python-3-exceptions/example.py, line 4, in max(weight)` подсказывает имя `max`.

## Python AttributeError

Еще одна распространенная ошибка `AttributeError`. Эта ошибка сообщает о том, что мы ищем у объекта атрибут, которого у него нет.

Например:

```
name = 'Dmitry'
name.last_name
```

Ошибка:

```
Traceback (most recent call last):
  File python-3-exceptions/example.py, line 2, in <module>
    name.last_name
AttributeError: 'str' object has no attribute 'last_name'
```

Точно такая же ошибка будет при попытке вызвать метод, которого у объекта нет:

```
name = 'Dmitry'
name.dance()
```

Ошибка:

```
Traceback (most recent call last):
  File python-3-exceptions/example.py, line 2, in <module>
    name.dance()
AttributeError: 'str' object has no attribute 'dance'
```

> В чем разница между методом и функцией? Метод это функция, которая принадлежит объекту. Функция же существует вне объектов, такие как `max`, `len`. Примеры методов `an_array.sort()` и `a_string.index('a pattern here')`. `an_array` и `a_string` это объекты и у них есть методы, которые мы можем вызывать. Это и есть различие между функцией и методом, в простом объяснении.

### Как исправить AttributeError

- из ошибки определите тип объекта и поймите с правильным типом ли вы работаете
- если тип объекта не тот, что вы ожидали проверьте как переменная была назначена или изменена в вашем коде
- если тип объекта правильный убедитесь что вы не допустили опечатку в имени атрибута или метода

Смотрите на тип объекта в AttributeError. `AttributeError: 'str' object has no attribute 'dance'` говорит о том что мы пытаемся получить доступ `dance` атрибуту, которого у объекта нет. Что важно, это тип объекта, о котором говорит ошибка. В примере это `str`, т.е. строка. Если вы посмотрите на [документацию к строкам](https://docs.python.org/3.7/library/stdtypes.html#string-methods) то убедитесь, что у строк нет методов или атрибутов `dance`.

> Атрибут это значение объекта которое можно получить по имени используя перед именем точку. Атрибутом объекта может быть переменная или метод. К примеру у объекта квадрат может быть атрибут сторона `square.side` и метод периметр `square.perimeter()`.

## Python IndentationError

Indentation (*рус. индентатион*) или отступы это размещение текста дальше вправо или влево, чтобы отделить его от окружающего текста.

 В программирования отступы используются для визуального обозначения вложенности одной части кода в другую. Такие части называются блоками.

```
# верхний уровень
for step in [3, 2, 1]:
    # блок for цикла первого вложенного уровня
    for stretch_step in ['с хвостиком', 'на ниточке', 'почти', 'ииии']:
        # блок for цикла второго вложенного уровня
        print(step, stretch_step)
# снова верхний уровень
print('... все!')
```

Для языка Python отступы очень важны. Они определяют вложенность кода.

К примеру в JavaScript отступы можно опустить и результат выполнения кода не измениться. Тот же код что выше написанный на JavaScript:

```
for (const step of [3, 2, 1]) {
  for (const stretch_step of ['с хвостиком', 'на ниточке', 'почти', 'ииии']) {
    console.log(step, stretch_step);
  }
}
console.log('... все!')
```

С игнорирование отступов. Обратите внимание на то как стало сложнее читать код.

```
for (const step of [3, 2, 1]) {
for (const stretchStep of ['с хвостиком', 'на ниточке', 'почти', 'ииии']) {
console.log(step, stretchStep);
}
}
console.log('... все!')
```

Вложенность позволяет понять какие переменные доступны на каждой строке кода. В последнем примере определить что `step` доступен на 3 строке уже слегка не удобно. В коде с двойной или тройной вложенностью и с количеством строк больше 20-30 это будет просто больно делать.

> Вложенность кода на 3 уровня уже должна вас насторожить. Такой код сложно читать и он требует реструктуризации. Правильный термин для реструктуризации рефакторинг. Тема рефакторинга интересная, большая и выходит за рамки данной статьи.

Вернемся к важности отступов в Python.

```
for step in [3, 2, 1]:
    for stetch_step in ['с хвостиком', 'на ниточке', 'почти', 'ииии']:
        print(step, stetch_step)
print('... все!')
```

Код выше совершенно другой от кода ниже:

```
for step in [3, 2, 1]:
for stetch_step in ['с хвостиком', 'на ниточке', 'почти', 'ииии']:
print(step, stetch_step)
print('... все!')
```

Что его выполнение вызовет ошибку:

```
  File python-3-exceptions/example.py, line 2
    for stetch_step in ['с хвостиком', 'на ниточке', 'почти', 'ииии']:
      ^
IndentationError: expected an indented block
```

Это и есть IndentatioError. Этот тип ошибок близок к SyntaxError тем что он говорит о неправильно написанном коде. Такой код язык понять не может.

> Тут под языком понимается интерпретатор кода Python, который способен перевести код понятный Python программисту в команды для процессора компьютера.

### Как исправить IndentationError

Обратитесь к указанной строке в ошибке. `File python-3-exceptions/example.py, line 2` говорит про стоку 2. На указанной в ошибке строке определите где вам не хватает отступов или их слишком много.

Исправте ошибку добавив или удалив отступы.

> Принятый стиль отступа это четыре пробела. Современные редакторы VSCode, Atom, Vim, Emacs и другие. Уже знают как помочь вам с отступами и даже создают их за вас. Настоятельно рекомендую использовать современные редакторы.

## Python ImportError

### Как исправить ImportError

- убедитесь что вы не назвали файл в котором происходит ошибка тем же именем которое не удается импортировать
- при импорте модулей созданных вами (другими словами файлы созданные вами) убедитесь что путь до него указан верно
- при импорте внешних пакетов убедитесь что имя пакета присутствует в requirements.txt файле, если его там нет установите пакет с командой pip

> Внешние пакеты это наборы модулей или один модуль созданный другими программистами и доступный для установки по имени этого пакета. Основные внешние пакеты вы можете найти на [https://pypi.org/](https://pypi.org/)

### Особено не понятная ошибка ImportError

Когда все выше указанные подсказки не работают то вы могли совершить следующую ошибку:

Не называйте файлы так же как уже существующие модули в Python. Например, не используйте `math.py` для имени ваших файлов так как это приведет к ошибкам импорта при использовании встроенного модуля `math`.

----

В данной статье были разобраны самые распространенные ошибки в языке Python 3, способы понять эти ошибки и исправить.

Здесь не рассмотрены все ошибки. Устанавливаемые внешние пакеты могут содержать свои собственные ошибки. Даже вы можете создавать свои собственные, новые ошибки.

Самое важное это вчитываться и стремиться к пониманию того что написано в заголовке ошибке и ее Traceback.

Когда будете писать свои ошибки стремитесь дать как можно более полезную информацию в заголовок ошибок. Так что бы другие программисты сказали вам спасибо за то что им не нужно разбираться что все таки произошло.
